### PR TITLE
MessageMonitorProcTest fix

### LINKED ISSUE #1633: MessageMonitorProcTest was killed
I deleted it at https://github.com/zerocracy/farm/commit/a52c61d96703ff2b102921e191774f3a1286423e because it didn't work, see http://www.rultor.com/t/15739-414909435 Let's put it back and make sure it actually compiles and works.

### PR DESCRIPTION
**Pull request by g4s8**
#1633 - reverted and fixed `MessageMonitorProcTest` test

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#1634](https://github.com/zerocracy/farm/issues/1634) is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2340640108); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

File: src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+                queue,
+                1,
+                1,
+                hook
+            ).exec(msg);
+            Mockito.verify(
+                sqs,
+                Mockito.timeout(Duration.ofMinutes(1).toMillis())
+                    .atLeastOnce()
+            ).changeMessageVisibilityBatch(
```
Comment (krzyk) [inline src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java]: @g4s8 lets move it to the next line, it will better match  parentheses

File: src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+                ArgumentMatchers.eq(queue), ArgumentMatchers.anyList()
```
Comment (krzyk) [inline src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java]: @g4s8 is that the change that fixed this test?
I see few other cosmetic ones (removed of parentheses and cast to long).

Comment (g4s8) [reply src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java]: @krzyk I've removed type casting because it's not needed anymore: `javafx.utils.Duration.toMillis()` uses `int` as return type, but `java.time.Duration` uses long`; parentheses was removed with auto-formatting in IDE.

**Comment by g4s8** [comment]
@krzyk fixed, please check

File: src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java (hunk 2 above)
Comment (krzyk) [reply src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java]: @g4s8 so the fix was removal `javafx.utils.Duration` -> `java.time.Duration`

File: src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+                queue,
+                1,
+                1,
+                hook
+            ).exec(msg);
+            Mockito.verify(
+                sqs,
+                Mockito.timeout(Duration.ofMinutes(1).toMillis()).atLeastOnce()
+            )
+            .changeMessageVisibilityBatch(
```
Comment (krzyk) [inline src/test/java/com/zerocracy/claims/proc/MessageMonitorProcTest.java]: @g4s8 actually this has to be indented (and the two lines below also)

**Comment by krzyk** [comment]
@rultor merge

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job was finished in 39 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1634](https://github.com/zerocracy/farm/issues/1634) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ypshenychka** [comment]
@krzyk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only two cosmetic issues were found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@krzyk thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +20 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
