### PR TITLE
Speed votes fix

### LINKED ISSUE #566: VsSpeed rates unknown people too high
Here is what [I see](https://www.0crat.com/footprint/C63314D6Z/460045609) for a person who hasn't done any tasks yet:

```
Average delivery time 0ms is no.1
```

It's wrong. We should give such a person the lowest position, if no jobs have been completed yet.

### PR DESCRIPTION
**Pull request by g4s8**
#566 - speed votes zero speed reproduced and fixed

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#796](https://github.com/zerocracy/farm/issues/796) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#796](https://github.com/zerocracy/farm/issues/796) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/711524638). The budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

File: src/main/java/com/zerocracy/pm/staff/votes/VsSpeed.java [hunk 1]
```diff
@@ -59,10 +59,17 @@ public VsSpeed(final Project pmo, final Collection<String> others) {
...
                     new Mapped<>(
-                        login -> new MapEntry<>(
-                            login,
-                            new Speed(pmo, login).bootstrap().avg()
-                        ),
+                        login -> {
+                            final double avg = new Speed(pmo, login)
+                                .bootstrap().avg();
+                            final double speed;
+                            if (avg == 0.0) {
```
Comment (carlosmiranda) [inline src/main/java/com/zerocracy/pm/staff/votes/VsSpeed.java]: @g4s8 instead of checking for `avg == 0.0`, which may be problematic since it's a floating point comparison, I think we should check if the person has done any jobs in the first place.

File: src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java [hunk 2]
```diff
@@ -33,40 +34,48 @@
...
 public final class VsSpeedTest {
-
     @Test
-    public void fastTest() throws Exception {
-        final FkProject pkt = new FkProject();
-        final String login = "user1";
-        final Speed speed = new Speed(pkt, login).bootstrap();
-        speed.add(
+    public void giveHigherVoteForFastSpeed() throws Exception {
+        final String one = "user2";
```
Comment (carlosmiranda) [inline src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java]: @g4s8 to give some more clarity to this test let's name the users (and variables) "fast" and "slow".

File: src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java [hunk 3]
```diff
@@ -33,40 +34,48 @@
...
-    public void slowTest() throws Exception {
-        final FkProject pkt = new FkProject();
-        final String login = "user2";
-        final Speed speed = new Speed(pkt, login).bootstrap();
-        speed.add(
-            "TST000002",
-            "gh:test/test#2",
-            TimeUnit.DAYS.toMinutes(9L)
+    public void giveZeroSpeedLowestVote() throws Exception {
+        final String one = "user_one";
```
Comment (carlosmiranda) [inline src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java]: @g4s8 same here, in this case let's call them something like "known" and "unknown"

File: src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java [hunk 4]
```diff
@@ -33,40 +34,48 @@
...
     @Test
-    public void slowTest() throws Exception {
-        final FkProject pkt = new FkProject();
-        final String login = "user2";
-        final Speed speed = new Speed(pkt, login).bootstrap();
-        speed.add(
-            "TST000002",
-            "gh:test/test#2",
-            TimeUnit.DAYS.toMinutes(9L)
+    public void giveZeroSpeedLowestVote() throws Exception {
```
Comment (carlosmiranda) [inline src/test/java/com/zerocracy/pm/staff/votes/VsSpeedTest.java]: @g4s8 Not clear why "zero speed" should have lowest vote. Of course we know because zero speed means no tickets yet but the name (and logic, as above) should reflect that.

**Comment by g4s8** [comment]
@carlosmiranda fixed in 758d8c2

**Comment by g4s8** [comment]
@carlosmiranda ping

**Comment by carlosmiranda** [comment]
@yegor256 good to merge. @g4s8 apologies for having missed this.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#796](https://github.com/zerocracy/farm/issues/796) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +20 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
