### PR TITLE
S3 upload fix

### LINKED ISSUE #987: SdkClientException: Unable to execute HTTP request: null
https://sentry.io/zerocracy/farm/issues/464802246/

```
ClosedChannelException: None
    at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
...
(45 additional frame(s) were not displayed)

SdkClientException: Unable to execute HTTP request: null
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
...
(14 additional frame(s) were not displayed)

Unable to execute HTTP request: null
```

### PR DESCRIPTION
**Pull request by g4s8**
#987 - read temp file to memory before uploading to S3.

`Files.newInputStream()` opens new stream in `S3Item` which was never closed,
AWS-sdk is working asynchronously, so actual stream reading operation was invoked in different thread than file stream was created, `Files.newInputStream` implemented is not very clear, but looks like it may close opened previously channel-stream.

This PR ensures that temporary file is fully read before uploading (sending data to another thread). Also now we close file stream for temporary file right after read it to memory.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#1065](https://github.com/zerocracy/farm/issues/1065) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#1065](https://github.com/zerocracy/farm/issues/1065) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1501855114); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewercom.zerocracy.Par@afd825a

File: src/main/java/com/zerocracy/farm/S3Item.java [hunk 1]
```diff
@@ -125,7 +133,24 @@ public void close() throws IOException {
...
+                    new LengthOf(
+                        new TeeInput(
+                            new InputOf(this.temp),
+                            new OutputTo(buff)
+                        )
+                    )
+                ).value()
+            );
+            this.ocket.write(
+                new ByteArrayInputStream(buff.toByteArray()),
```
Comment (carlosmiranda) [inline src/main/java/com/zerocracy/farm/S3Item.java]: @g4s8 maybe we can do this, and do away with `ByteArrayOutputStream` altogether?

```java
new ByteArrayInputStream(
  new InputAsBytes(
    new PathAsInput(this.temp)
  ).asBytes()
)
```

**Comment by g4s8** [comment]
@carlosmiranda fixed, please look at 9caf174

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1065](https://github.com/zerocracy/farm/issues/1065) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>The code reviewer found at least three problems in the code.
Comments were mostly about design problems, not cosmetic issues.

Only one issue was found during code review. 
Please confirm that you'll try to find at least three major problems while future reviews.

**Comment by g4s8** [comment]
@yegor256 can you release new version with this PR to check the fix?

**Comment by ypshenychka** [comment]
@carlosmiranda ping

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda Thanks!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
